import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: "perlinNoise",
  contractVersion: "1.0.0",
  opId: "perlin_noise",
  label: "Perlin 噪声",
  nameEn: "PerlinNoise",
  description: "Perlin noise first table. Frequency and offset are index-space. aw_perlin_noise presets stay in .generator.ts.",
  inputs: [
    {
      name: "columns",
      type: "number",
      access: "item",
      defaultValue: 16,
      mode: "parameter",
      label: "列",
    },
    {
      name: "rows",
      type: "number",
      access: "item",
      defaultValue: 16,
      mode: "parameter",
      label: "行",
    },
    {
      name: "seed",
      type: "number",
      access: "item",
      defaultValue: 1337,
      mode: "parameter",
      label: "种子",
    },
    {
      name: "frequency",
      type: "number",
      access: "item",
      defaultValue: 0.08,
      mode: "parameter",
      description: "Index-space frequency. Not world metres.",
      label: "频率",
    },
    {
      name: "fractal",
      type: "string",
      access: "item",
      defaultValue: "none",
      mode: "parameter",
      options: [
        "none",
        "fbm",
        "ridged",
        "pingpong",
      ],
      label: "分形",
    },
    {
      name: "octaves",
      type: "number",
      access: "item",
      defaultValue: 4,
      mode: "parameter",
      label: "层数",
    },
    {
      name: "lacunarity",
      type: "number",
      access: "item",
      defaultValue: 2,
      mode: "parameter",
      label: "间隙",
    },
    {
      name: "gain",
      type: "number",
      access: "item",
      defaultValue: 0.5,
      mode: "parameter",
      label: "增益",
    },
    {
      name: "offsetX",
      type: "number",
      access: "item",
      defaultValue: 0,
      mode: "parameter",
      label: "偏移X",
    },
    {
      name: "offsetY",
      type: "number",
      access: "item",
      defaultValue: 0,
      mode: "parameter",
      label: "偏移Y",
    },
  ],
  outputs: [
    {
      name: "grid",
      type: "grid",
      runtimeType: "grid",
      access: "item",
      label: "网格",
    },
  ],
  deterministic: true,
})
