import { existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { appRoot as compositionRoot } from '../resources.js'

const repoRoot = resolve(compositionRoot, '..', '..')
const commonRoot = existsSync(resolve(compositionRoot, 'shared-batteries'))
  ? resolve(compositionRoot, 'shared-batteries')
  : resolve(repoRoot, 'packages/batteries-common/batteries')

export const FIRST_BATCH_COMPOSITION_BATTERIES = [
  'Modeling/layout/allocate_spans',
  'Modeling/layout/segment_run',
  'Basic/random/derive_seed',
  'Modeling/pose/local_frame',
  'Modeling/pose/fit_anchor',
  'Modeling/query/bounds_relation',

  'Modeling/geometry2d/point2d',
  'Modeling/geometry2d/base_plane',
  'Modeling/geometry2d/polyline2d',
  'Modeling/geometry2d/spline2d',
  'Modeling/geometry2d/network2d',
  'Modeling/geometry2d/polygon2d',
  'Modeling/geometry2d/geometry_mask',
  'Modeling/geometry3d/point3d',
  'Modeling/geometry3d/polyline3d',
  'Modeling/geometry3d/spline3d',
  'Modeling/geometry3d/polygon3d',
  'Modeling/geometry3d/network3d',
  'Modeling/surface/lift_to_surface',
  'Modeling/surface/surface_band',
  'Grid/init/create_grid',
  'Grid/init/grid_fill',
  'Grid/init/grid_gradient',
  'Grid/init/grid_diamond_square',
  'Grid/init/grid_midpoint',
  'Grid/noise/hash_noise',
  'Grid/noise/value_noise',
  'Grid/noise/value_cubic_noise',
  'Grid/noise/perlin_noise',
  'Grid/noise/opensimplex2_noise',
  'Grid/noise/opensimplex2s_noise',
  'Grid/noise/cellular_noise',
  'Grid/arith/grid_add',
  'Grid/arith/grid_sub',
  'Grid/arith/grid_mul',
  'Grid/arith/grid_min',
  'Grid/arith/grid_max',
  'Grid/arith/grid_lerp',
  'Grid/arith/grid_choose',
  'Grid/arith/grid_mask_diff',
  'Grid/arith/grid_mask_union',
  'Grid/arith/grid_abs',
  'Grid/arith/grid_neg',
  'Grid/arith/grid_clamp',
  'Grid/arith/grid_remap',
  'Grid/arith/grid_smoothstep',
  'Grid/arith/grid_quantize',
  'Grid/filter/grid_blur',
  'Grid/filter/grid_sharpen',
  'Grid/filter/grid_median',
  'Grid/filter/grid_neighborhood_min',
  'Grid/filter/grid_neighborhood_max',
  'Grid/morph/grid_dilate',
  'Grid/morph/grid_erode_morph',
  'Grid/morph/grid_open',
  'Grid/morph/grid_close',
  'Grid/morph/grid_majority',
  'Grid/morph/grid_outline',
  'Grid/derive/grid_slope',
  'Grid/derive/grid_aspect',
  'Grid/derive/grid_curvature',
  'Grid/derive/grid_threshold',
  'Grid/derive/grid_range_select',
  'Grid/derive/grid_edge',
  'Grid/derive/grid_bbox',
  'Grid/partition/grid_components',
  'Grid/zone/grid_zonal_mean',
  'Grid/global/grid_stats',
  'Grid/global/grid_distance',
  'Grid/lattice/grid_resize',
  'Modeling/heightfield/heightfield',
  'Modeling/heightfield/heightfield_explode',
  'Modeling/heightfield/heightfield_set_mask',
  'Modeling/heightfield/heightfield_mesh',
  'Modeling/geometry3d/box',
  'Modeling/pose/transform',
  'Modeling/pose/place_on_ground',
  'Scene/manage/empty_scene',
  'Scene/bridge/scene_node',
  'Scene/manage/add_child',
  'Scene/output/scene_output',
] as const

export const FIRST_BATCH_COMMON_BATTERIES = [
  'Basic/input/numberConst',
  'Basic/input/textPanel',
  'Basic/input/toggle',
  'Basic/input/jsonPanel',
] as const

export const FIRST_BATCH_OP_IDS = [
  'allocate_spans',
  'segment_run',
  'derive_seed',
  'local_frame',
  'fit_anchor',
  'bounds_relation',
  'point2d',
  'base_plane',
  'polyline2d',
  'spline2d',
  'network2d',
  'polygon2d',
  'geometry_mask',
  'point3d',
  'polyline3d',
  'spline3d',
  'polygon3d',
  'network3d',
  'lift_to_surface',
  'surface_band',
  'create_grid',
  'grid_fill',
  'grid_gradient',
  'grid_diamond_square',
  'grid_midpoint',
  'hash_noise',
  'value_noise',
  'value_cubic_noise',
  'perlin_noise',
  'opensimplex2_noise',
  'opensimplex2s_noise',
  'cellular_noise',
  'grid_add',
  'grid_sub',
  'grid_mul',
  'grid_min',
  'grid_max',
  'grid_lerp',
  'grid_choose',
  'grid_mask_diff',
  'grid_mask_union',
  'grid_abs',
  'grid_neg',
  'grid_clamp',
  'grid_remap',
  'grid_smoothstep',
  'grid_quantize',
  'grid_blur',
  'grid_sharpen',
  'grid_median',
  'grid_neighborhood_min',
  'grid_neighborhood_max',
  'grid_dilate',
  'grid_erode_morph',
  'grid_open',
  'grid_close',
  'grid_majority',
  'grid_outline',
  'grid_slope',
  'grid_aspect',
  'grid_curvature',
  'grid_threshold',
  'grid_range_select',
  'grid_edge',
  'grid_bbox',
  'grid_components',
  'grid_zonal_mean',
  'grid_stats',
  'grid_distance',
  'grid_resize',
  'heightfield',
  'heightfield_explode',
  'heightfield_set_mask',
  'heightfield_mesh',
  'box',
  'transform',
  'place_on_ground',
  'empty_scene',
  'scene_node',
  'add_child',
  'scene_output',
  'number_const',
  'text_panel',
  'toggle',
  'json_panel',
] as const

function existing(paths: string[]): string[] {
  return paths.filter((dir) => existsSync(dir))
}

/** Only the first-batch library dirs. Obsolete batteries are not scanned. */
export function resolveSceneBatteryScanRoots(): string[] {
  return existing([
    ...FIRST_BATCH_COMMON_BATTERIES.map((rel) => resolve(commonRoot, rel)),
    ...FIRST_BATCH_COMPOSITION_BATTERIES.map((rel) => resolve(compositionRoot, 'batteries', rel)),
  ])
}

export function resolveSceneContractRoots(): string[] {
  return resolveSceneBatteryScanRoots()
}

const LIBRARY_EXPORTS = {
  'Modeling/layout/allocate_spans': 'allocateSpans',
  'Modeling/layout/segment_run': 'segmentRun',
  'Basic/random/derive_seed': 'deriveSeed',
  'Modeling/pose/local_frame': 'localFrame',
  'Modeling/pose/fit_anchor': 'fitAnchor',
  'Modeling/query/bounds_relation': 'boundsRelation',

  'Modeling/geometry2d/point2d': 'point2d',
  'Modeling/geometry2d/base_plane': 'basePlane',
  'Modeling/geometry2d/polyline2d': 'polyline2d',
  'Modeling/geometry2d/spline2d': 'spline2d',
  'Modeling/geometry2d/network2d': 'network2d',
  'Modeling/geometry2d/polygon2d': 'polygon2d',
  'Modeling/geometry2d/geometry_mask': 'geometryMask',
  'Modeling/geometry3d/point3d': 'point3d',
  'Modeling/geometry3d/polyline3d': 'polyline3d',
  'Modeling/geometry3d/spline3d': 'spline3d',
  'Modeling/geometry3d/polygon3d': 'polygon3d',
  'Modeling/geometry3d/network3d': 'network3d',
  'Modeling/surface/lift_to_surface': 'liftToSurface',
  'Modeling/surface/surface_band': 'surfaceBand',
  'Grid/init/create_grid': 'createGrid',
  'Grid/init/grid_fill': 'gridFill',
  'Grid/init/grid_gradient': 'gridGradient',
  'Grid/init/grid_diamond_square': 'gridDiamondSquare',
  'Grid/init/grid_midpoint': 'gridMidpoint',
  'Grid/noise/hash_noise': 'hashNoise',
  'Grid/noise/value_noise': 'valueNoise',
  'Grid/noise/value_cubic_noise': 'valueCubicNoise',
  'Grid/noise/perlin_noise': 'perlinNoise',
  'Grid/noise/opensimplex2_noise': 'openSimplex2Noise',
  'Grid/noise/opensimplex2s_noise': 'openSimplex2sNoise',
  'Grid/noise/cellular_noise': 'cellularNoise',
  'Grid/arith/grid_add': 'gridAdd',
  'Grid/arith/grid_sub': 'gridSub',
  'Grid/arith/grid_mul': 'gridMul',
  'Grid/arith/grid_min': 'gridMin',
  'Grid/arith/grid_max': 'gridMax',
  'Grid/arith/grid_lerp': 'gridLerp',
  'Grid/arith/grid_choose': 'gridChoose',
  'Grid/arith/grid_mask_diff': 'gridMaskDiff',
  'Grid/arith/grid_mask_union': 'gridMaskUnion',
  'Grid/arith/grid_abs': 'gridAbs',
  'Grid/arith/grid_neg': 'gridNeg',
  'Grid/arith/grid_clamp': 'gridClamp',
  'Grid/arith/grid_remap': 'gridRemap',
  'Grid/arith/grid_smoothstep': 'gridSmoothstep',
  'Grid/arith/grid_quantize': 'gridQuantize',
  'Grid/filter/grid_blur': 'gridBlur',
  'Grid/filter/grid_sharpen': 'gridSharpen',
  'Grid/filter/grid_median': 'gridMedian',
  'Grid/filter/grid_neighborhood_min': 'gridNeighborhoodMin',
  'Grid/filter/grid_neighborhood_max': 'gridNeighborhoodMax',
  'Grid/morph/grid_dilate': 'gridDilate',
  'Grid/morph/grid_erode_morph': 'gridErodeMorph',
  'Grid/morph/grid_open': 'gridOpen',
  'Grid/morph/grid_close': 'gridClose',
  'Grid/morph/grid_majority': 'gridMajority',
  'Grid/morph/grid_outline': 'gridOutline',
  'Grid/derive/grid_slope': 'gridSlope',
  'Grid/derive/grid_aspect': 'gridAspect',
  'Grid/derive/grid_curvature': 'gridCurvature',
  'Grid/derive/grid_threshold': 'gridThreshold',
  'Grid/derive/grid_range_select': 'gridRangeSelect',
  'Grid/derive/grid_edge': 'gridEdge',
  'Grid/derive/grid_bbox': 'gridBBox',
  'Grid/partition/grid_components': 'gridComponents',
  'Grid/zone/grid_zonal_mean': 'gridZonalMean',
  'Grid/global/grid_stats': 'gridStats',
  'Grid/global/grid_distance': 'gridDistance',
  'Grid/lattice/grid_resize': 'gridResize',
  'Modeling/heightfield/heightfield': 'heightfield',
  'Modeling/heightfield/heightfield_explode': 'heightfieldExplode',
  'Modeling/heightfield/heightfield_set_mask': 'heightfieldSetMask',
  'Modeling/heightfield/heightfield_mesh': 'heightfieldMesh',
  'Modeling/geometry3d/box': 'box',
  'Modeling/pose/transform': 'transform',
  'Modeling/pose/place_on_ground': 'placeOnGround',
  'Scene/manage/empty_scene': 'emptyScene',
  'Scene/bridge/scene_node': 'sceneNode',
  'Scene/manage/add_child': 'addChild',
  'Scene/output/scene_output': 'sceneOutput',
} as const satisfies Record<(typeof FIRST_BATCH_COMPOSITION_BATTERIES)[number], string>

/** On-disk first-batch function files. Scene Script imports these as TypeScript. */
export function resolveFirstBatchLibraryEntries(): ReadonlyArray<{ file: string; exportName: string }> {
  return FIRST_BATCH_COMPOSITION_BATTERIES.map((rel) => ({
    file: resolve(compositionRoot, 'batteries', rel, existsSync(resolve(compositionRoot, 'batteries', rel, 'index.ts')) ? 'index.ts' : 'index.js'),
    exportName: LIBRARY_EXPORTS[rel],
  }))
}
