// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/decorations/PoiScatter/PoiScatter.generated.json
// @scene-id definition:batteries.templates.structures.decorations.poi-scatter.poi-scatter-generated.nested.0
const poiScatterTemplateObjectAssetName = defineGroup(
  {
    id: "scene.template.poi-scatter.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id ps-an-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name"},
      })

    // @scene-id ps-an-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type"},
      })

    // @scene-id ps-an-obj
    const textPanel3 = textPanel({
        "$params": {"text":"object"},
      })

    // @scene-id ps-an-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id ps-an-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id ps-an-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.decorations.poi-scatter.poi-scatter-generated
export const poiScatterTemplate = defineGroup(
  {
    id: "scene.template.poi-scatter",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0, labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "item", order: 1, labelEn: "AssetName" },
      poiRules: { type: StringValue, runtimeType: "string", runtimePort: "in_2", order: 2, labelEn: "PoiRules" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", order: 3, labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item", order: 0, labelEn: "Scene" },
      poi: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "item", order: 1, labelEn: "Poi" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "item", order: 2, labelEn: "Rest" },
      poiPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "PoiPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, poiRules, seed }) => {
    // @scene-id ps-pt
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id ps-ex
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ps-rg
    const rectangularGrid3 = rectangularGrid({
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id ps-vs
    const voxelSlice4 = voxelSlice({
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id ps-zone
    const numberValue5 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id ps-zadd
    const basicMathOp6 = basicMathOp({
        "$params": {"op":"+"},
        "a": voxelSlice4.z,
        "b": numberValue5.value,
      })

    // @scene-id ps-zr
    const rangeList7 = rangeList({
        "start": basicMathOp6.result,
        "end": basicMathOp6.result,
      })

    // @scene-id ps-bat
    const poiScatter8 = poiScatter({
        "assetNames": assetName,
        "poiRules": poiRules,
        "seed": seed,
        "inputGrid": voxelSlice4.slice,
      })

    // @scene-id ps-txd
    const textPanel9 = textPanel({
        "$params": {"text":"poi"},
      })

    // @scene-id ps-g2d
    const gridSceneNode10 = gridSceneNode({
        "grid": poiScatter8.outputGrid,
        "name": textPanel9.output,
        "zRange": rangeList7.list,
      })

    // @scene-id group_ps_objasset
    const poiScatterTemplateObjectAssetName11 = poiScatterTemplateObjectAssetName({
        "input0": gridSceneNode10.scene,
        "input1": poiScatter8.outputAssetNames,
      })

    // @scene-id ps-ac1
    const addSceneChildren12 = addSceneChildren({
        "nodes": poiScatterTemplateObjectAssetName11.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ps-sub
    const algRegionSubtract13 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": poiScatter8.outputGrid,
      })

    // @scene-id ps-txr
    const textPanel14 = textPanel({
        "$params": {"text":"rest"},
      })

    // @scene-id ps-g2r
    const gridSceneNode15 = gridSceneNode({
        "grid": algRegionSubtract13.region,
        "name": textPanel14.output,
      })

    // @scene-id ps-ac2
    const addSceneChildren16 = addSceneChildren({
        "nodes": gridSceneNode15.scene,
        "scene": addSceneChildren12.scene,
      })

    // @scene-id ps-fpd
    const sceneFocusPath17 = sceneFocusPath({
        "scene": addSceneChildren16.scene,
        "path": addSceneChildren12.childPaths,
      })

    // @scene-id ps-fpr
    const sceneFocusPath18 = sceneFocusPath({
        "scene": addSceneChildren16.scene,
        "path": addSceneChildren16.childPaths,
      })

    // @scene-id ps-tsd
    const stringValue19 = stringValue({
        "value": addSceneChildren12.childPaths,
      })

    // @scene-id ps-tsr
    const stringValue20 = stringValue({
        "value": addSceneChildren16.childPaths,
      })
    return {
      scene: addSceneChildren16.scene,
      poi: sceneFocusPath17.scene,
      rest: sceneFocusPath18.scene,
      poiPath: stringValue19.value,
      restPath: stringValue20.value,
    }
  },
)
