import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'geometryMask',
  contractVersion: '1.0.0',
  opId: 'geometry_mask',
  label: '几何遮罩',
  nameEn: 'GeometryMask',
  description: 'Burn operating Geometry into a 0–1 Grid on plane + columns + rows. Width and feather are metres on this consumer, not on the Geometry.',
  inputs: [
    {
      name: 'plane',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'World-metre plane the lattice covers. Same origin / width / height / +Y as heightfield.',
      label: '平面',
    },
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'Operating Geometry to burn (point2d / plane / polyline / spline / polygon / network).',
      label: '几何',
    },
    {
      name: 'columns',
      type: 'number',
      access: 'item',
      required: true,
      mode: 'parameter',
      description: 'Lattice columns. Must match the terrain grid to stay aligned.',
      label: '列',
    },
    {
      name: 'rows',
      type: 'number',
      access: 'item',
      required: true,
      mode: 'parameter',
      description: 'Lattice rows. Must match the terrain grid to stay aligned.',
      label: '行',
    },
    {
      name: 'width',
      type: 'number',
      access: 'item',
      required: false,
      defaultValue: 0,
      mode: 'parameter',
      description: 'Corridor diameter in metres for point / curve / network. Ignored for filled polygon and plane.',
      label: '宽度',
    },
    {
      name: 'feather',
      type: 'number',
      access: 'item',
      required: false,
      defaultValue: 0,
      mode: 'parameter',
      description: 'World-metre falloff outside the hard region. 0 is binary.',
      label: '羽化',
    },
  ],
  outputs: [
    {
      name: 'grid',
      type: 'grid',
      runtimeType: 'grid',
      access: 'item',
      description: 'Same-lattice 0–1 mask. Cells outside the burn are 0.',
      label: '网格',
    },
  ],
  deterministic: true,
})
