import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'pointsAlongPolyline',
  contractVersion: '1.0.0',
  opId: 'points_along_polyline',
  description: 'Generates plot footprint points distributed along a polyline with normal offsets.',
  inputs: [
    {
      name: 'points',
      type: 'point2d',
      access: 'list',
      required: true,
      description: 'Road control point list.',
      label: '控制折线',
    },
    {
      name: 'count',
      type: 'number',
      access: 'item',
      defaultValue: 4,
      description: 'Number of house plots along the road.',
      label: '地块数量',
      mode: 'parameter',
      control: true,
    },
    {
      name: 'offset',
      type: 'number',
      access: 'item',
      defaultValue: 4,
      description: 'Fallback normal offset when no roadWidth/widths is provided.',
      label: '法向偏移',
      mode: 'parameter',
    },
    {
      name: 'margin',
      type: 'number',
      access: 'item',
      defaultValue: 2.2,
      description: 'Extra setback beyond local half-width when widths or roadWidth is provided.',
      label: '宅基退距',
      mode: 'parameter',
    },
    {
      name: 'roadWidth',
      type: 'number',
      access: 'item',
      description: 'Global road width used when widths is empty.',
      label: '路宽',
      mode: 'parameter',
    },
    {
      name: 'widths',
      type: 'number',
      access: 'list',
      description: 'Per-sample or profile widths from spline_sample.',
      label: '宽度剖面',
    },
    {
      name: 'seed',
      type: 'number',
      access: 'item',
      defaultValue: 1,
      description: 'Random seed for jitter.',
      label: '随机种子',
      mode: 'parameter',
    },
  ],
  outputs: [
    {
      name: 'points',
      type: 'point2d',
      access: 'list',
      description: 'List of generated plot points.',
      label: '地块点列',
    },
    {
      name: 'yaw',
      type: 'number',
      access: 'list',
      description: 'Road tangent heading at each plot, radians.',
      label: '朝向',
    },
    {
      name: 'count',
      type: 'number',
      access: 'item',
      description: 'Number of plots produced.',
      label: '生成数',
    },
  ],
  deterministic: true,
})
