import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'placeOnGround',
  contractVersion: '1.0.0',
  opId: 'place_on_ground',
  label: '贴地',
  nameEn: 'PlaceOnGround',
  description: 'Sit a local hangable mesh on the Heightfield at (x, y). Uses the AABB floor centre and the same height channel as sampleHeight. Keep upright; yaw is radians about +Z. Scatter loops should call sampleHeight instead so the graph does not explode.',
  inputs: [
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'Hangable Geometry kind mesh. Local origin may be anywhere; contact is the mesh bottom.',
      label: '几何',
    },
    {
      name: 'heightfield',
      type: 'heightfield',
      runtimeType: 'heightfield',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'The same Heightfield packet heightfieldMesh wove.',
      label: '高度场',
    },
    {
      name: 'x',
      type: 'number',
      access: 'item',
      required: true,
      mode: 'parameter',
      label: 'X',
    },
    {
      name: 'y',
      type: 'number',
      access: 'item',
      required: true,
      mode: 'parameter',
      label: 'Y',
    },
    {
      name: 'yaw',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      description: 'Radians around world +Z. The mesh stays upright.',
      label: '偏航',
    },
    {
      name: 'offset',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      description: 'Metres along +Z after sitting. Positive lifts; negative buries the contact.',
      label: '抬升',
    },
  ],
  outputs: [
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      description: 'World-space mesh whose bottom sits on the terrain.',
      label: '几何',
    },
  ],
  deterministic: true,
})
