import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'transform',
  contractVersion: '1.0.0',
  opId: 'transform',
  label: '变换',
  nameEn: 'Transform',
  description: 'Put a local hangable mesh into the world. The mesh origin moves to (x, y, z). Yaw is radians about +Z; the object stays upright. To sit on terrain, use placeOnGround.',
  inputs: [
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'Hangable Geometry kind mesh in local metres.',
      label: '几何',
    },
    {
      name: 'x',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      label: 'X',
    },
    {
      name: 'y',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      label: 'Y',
    },
    {
      name: 'z',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      description: 'World Z of the mesh origin. Not terrain height unless you sampled it.',
      label: 'Z',
    },
    {
      name: 'yaw',
      type: 'number',
      access: 'item',
      defaultValue: 0,
      mode: 'parameter',
      description: 'Radians around world +Z. Keep upright.',
      label: '偏航',
    },
    {
      name: 'scale',
      type: 'number',
      access: 'item',
      defaultValue: 1,
      mode: 'parameter',
      description: 'Uniform scale about the local origin.',
      label: '缩放',
    },
  ],
  outputs: [
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      description: 'The same mesh in world metres.',
      label: '几何',
    },
  ],
  deterministic: true,
})
