import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: "cellularNoise",
  contractVersion: "1.0.0",
  opId: "cellular_noise",
  label: "Cellular 噪声",
  nameEn: "CellularNoise",
  description: "Cellular / Worley first table. Extra ports: distanceFunction, returnType, jitter. Not a CA step.",
  inputs: [
    {
      name: "columns",
      type: "number",
      access: "item",
      defaultValue: 16,
      mode: "parameter",
      label: "列",
    },
    {
      name: "rows",
      type: "number",
      access: "item",
      defaultValue: 16,
      mode: "parameter",
      label: "行",
    },
    {
      name: "seed",
      type: "number",
      access: "item",
      defaultValue: 1337,
      mode: "parameter",
      label: "种子",
    },
    {
      name: "frequency",
      type: "number",
      access: "item",
      defaultValue: 0.08,
      mode: "parameter",
      description: "Index-space frequency. Not world metres.",
      label: "频率",
    },
    {
      name: "fractal",
      type: "string",
      access: "item",
      defaultValue: "none",
      mode: "parameter",
      options: [
        "none",
        "fbm",
        "ridged",
        "pingpong",
      ],
      label: "分形",
    },
    {
      name: "octaves",
      type: "number",
      access: "item",
      defaultValue: 4,
      mode: "parameter",
      label: "层数",
    },
    {
      name: "lacunarity",
      type: "number",
      access: "item",
      defaultValue: 2,
      mode: "parameter",
      label: "间隙",
    },
    {
      name: "gain",
      type: "number",
      access: "item",
      defaultValue: 0.5,
      mode: "parameter",
      label: "增益",
    },
    {
      name: "offsetX",
      type: "number",
      access: "item",
      defaultValue: 0,
      mode: "parameter",
      label: "偏移X",
    },
    {
      name: "offsetY",
      type: "number",
      access: "item",
      defaultValue: 0,
      mode: "parameter",
      label: "偏移Y",
    },
    {
      name: "distanceFunction",
      type: "string",
      access: "item",
      defaultValue: "euclideanSq",
      mode: "parameter",
      options: [
        "euclidean",
        "euclideanSq",
        "manhattan",
        "hybrid",
      ],
      label: "距离",
    },
    {
      name: "returnType",
      type: "string",
      access: "item",
      defaultValue: "distance",
      mode: "parameter",
      options: [
        "cellValue",
        "distance",
        "distance2",
        "distance2Add",
        "distance2Sub",
        "distance2Mul",
        "distance2Div",
      ],
      label: "返回",
    },
    {
      name: "jitter",
      type: "number",
      access: "item",
      defaultValue: 1,
      mode: "parameter",
      label: "抖动",
    },
  ],
  outputs: [
    {
      name: "grid",
      type: "grid",
      runtimeType: "grid",
      access: "item",
      label: "网格",
    },
  ],
  deterministic: true,
})
