import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'surfaceBand',
  contractVersion: '1.0.0',
  opId: 'surface_band',
  label: '曲面带宽',
  nameEn: 'SurfaceBand',
  description: 'Minkowski band of a 3D skeleton sat on a hangable mesh. Width is metres on this call, not on the Geometry. Builds its own stadium strips and node disks; does not clip the input triangulation. geodesic offsets in the tangent plane; plan uses XY capsules. One hangable mesh.',
  inputs: [
    {
      name: 'mesh',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: 'Hangable Geometry kind mesh. The surface the constructed band sits on.',
      label: '网格',
    },
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      required: true,
      mode: 'value',
      description: '3D skeleton already on the mesh: point3d / polyline3d / spline3d / network3d. Lift 2D Geometry first. Not a polygon.',
      label: '几何',
    },
    {
      name: 'width',
      type: 'number',
      access: 'item',
      required: true,
      mode: 'parameter',
      description: 'Full corridor width in metres (surface metres when geodesic, plan metres when plan).',
      label: '宽度',
    },
    {
      name: 'widths',
      type: 'number',
      access: 'list',
      required: false,
      mode: 'value',
      description: 'Optional per-point or per-node full widths. Polyline/spline: one per authored point. Network: one per node, lerp along edges. Length mismatch is { error }.',
      label: '宽度列',
    },
    {
      name: 'metric',
      type: 'string',
      access: 'item',
      required: false,
      defaultValue: 'geodesic',
      mode: 'parameter',
      options: ['geodesic', 'plan'],
      description: 'geodesic: tangent-plane offset, closest-point sit. plan: XY stadium, vertical sit.',
      label: '度量',
    },
    {
      name: 'offset',
      type: 'number',
      access: 'item',
      required: false,
      defaultValue: 0,
      mode: 'parameter',
      description: 'Metres after the band is built. plan uses +Z; geodesic uses the sat vertex normal. 0 leaves the band on the surface.',
      label: '抬升',
    },
  ],
  outputs: [
    {
      name: 'geometry',
      type: 'geometry',
      runtimeType: 'geometry',
      access: 'item',
      description: 'One hangable mesh: the constructed band.',
      label: '几何',
    },
  ],
  deterministic: true,
})
