import { resolvePackSchemaVersion, type PackSchemaVersion } from './inputs.js'
import type { PackProjection } from './engineBridge.js'
import { emitV1Declarations } from './emitPackV1.js'

/** Emits an explicitly selected Engine Pack protocol (default 2.0.0, Engine 0.3.3). Engine SDK imports belong only
 * to the generated consumer artifact; this application has no Engine dependency.
 */

export interface EmitPackInput {
  readonly schemaVersion?: PackSchemaVersion
  /** Required by v1's declaration-only catalog; ignored by the v2 emitter. */
  readonly projection?: PackProjection
  /** Tile packs can use the lighting already owned by their containing scene. */
  readonly includeDefaultLighting?: boolean
  readonly parameters?: readonly Record<string, unknown>[]
  readonly args?: readonly unknown[]
  readonly parameterBindings?: Readonly<Record<string, { argument: number; path: readonly string[] }>>
  readonly packageUuid: string
  readonly packName: string
  /** Last segment of the scene asset key, `scene/<sceneSlug>`. */
  readonly sceneSlug: string
  readonly sceneKey?: string

}

export function emitPackSource(input: EmitPackInput): string {
  const { packageUuid, packName, sceneSlug } = input
  const v1 = resolvePackSchemaVersion(input.schemaVersion) === '1.0.0'
  if (v1 && !input.projection) throw new Error('schemaVersion 1.0.0 requires the export-time projection for asset declarations')
  if (v1 && (input.parameters?.length || Object.keys(input.parameterBindings ?? {}).length))
    throw new Error('schemaVersion 1.0.0 supports fixed args only; parameter bindings require 2.0.0')
  const sdk = v1 ? '@forgeax/engine-' : '@forgeax/engine/'
  return `// Generated by scene-generator pack export. Edit scene/*.ts and run pack:rebuild to regenerate the executable closure.
//
// Catalog initialization is declaration-only. Native build owns generation.
import { meshFromInterleaved, packInterleavedVertexAttributes } from '${sdk}geometry'
${v1 ? "import { AssetGuid } from '@forgeax/engine-pack/guid'\nimport type { ScriptablePackDefinition } from '@forgeax/engine-pack/source'" : "import { AssetGuid, definePack, definePackageId } from '@forgeax/engine/pack/source'"}
import { DirectionalLight, Materials, MeshFilter, MeshRenderer, Skylight } from '${sdk}render'
import { ChildOf, Name, Transform } from '${sdk}scene'
import type {
  AssetGuid as AssetGuidType,
  LocalEntityId,
  MaterialAsset,
  TextureAsset,
  SamplerAsset,
  MeshAsset,
  SceneAsset,
  SceneEntity,
} from '${sdk}types'
import { ok } from '${sdk}types'

import { projectScene, Y_UP_QUAT, collectMaterialTextures, decodeSurfaceTexture, surfaceTextureKey, SURFACE_TEXTURE_CHANNELS } from './platform/engineBridge.ts'
import { generateScene } from './build-scene.${v1 ? 'ts' : 'mjs'}'

${v1 ? emitV1Declarations(input.projection!, packageUuid, input.sceneKey ?? `scene/${sceneSlug}`, packName) : ''}
const SCENE_KEY = ${JSON.stringify(input.sceneKey ?? `scene/${sceneSlug}`)}

/** Scene space is +Z up, the engine is +Y up: every authored entity hangs off this root. */
const AXIS_ROOT = ${v1 ? '0' : "'axis-root'"}

/**
 * Default lighting. Values follow the engine's own reference scene
 * (\`templates/game-3d/assets/scene.pack.ts\` "Sun" / "Analytic Skylight"); the
 * skylight drops the equirect so it stays a solid-colour ambient with no
 * external asset and no async IBL upload — the pack has to be self-contained,
 * and the analytic path is lit on the first frame.
 *
 * Lights are top-level, NOT children of AXIS_ROOT: \`DirectionalLight.direction\`
 * is a world-space outgoing vector with no Transform dependency, so it is
 * already expressed in the engine's +Y-up frame.
 */
const SUN_OUTGOING_DIRECTION: readonly [number, number, number] = [-0.32, -0.91, -0.24]

/**
 * Shadow coverage in metres, sized off the scene rather than fixed. The map is
 * 2048 texels wide, so coverage past ~512 m exceeds a 0.25 m texel and the
 * shadows turn to mush; below ~64 m the cascades waste their resolution.
 */
function shadowDistanceFor(diagonal: number): number {
  return Math.round(Math.min(512, Math.max(64, diagonal)))
}

export default ${v1 ? '' : 'definePack('}{
  schemaVersion: '${v1 ? '1.0.0' : '2.0.0'}',
  packageId: ${v1 ? 'guid' : 'definePackageId'}('${packageUuid}'),
  name: ${JSON.stringify(packName)},
  ${v1 ? 'assets,\n  externalAssets: {},' : ''}
  ${input.parameters?.length ? `parameters: ${JSON.stringify(input.parameters)},` : ''}
  sceneComponents: [ChildOf, DirectionalLight, MeshFilter, MeshRenderer, Name, Skylight, Transform],
  build: async (${v1 ? '' : 'context'}) => {
    const args: any[] = ${JSON.stringify(input.args ?? [])};
    ${v1 || !input.parameters?.length ? '' : `const bindings: Record<string, {argument:number;path:string[]}> = ${JSON.stringify(input.parameterBindings ?? {})};
    for (const [name, binding] of Object.entries(bindings)) {
      let owner: any = args;
      const path = [binding.argument, ...binding.path];
      for (let i = 0; i < path.length - 1; i++) owner = owner[path[i]];
      if (context.values && Object.hasOwn(context.values, name)) owner[path[path.length - 1]!] = (context.values as Record<string, unknown>)[name];
    }`}
    const assetGuid = (key: string) => ${v1 ? 'assets[key]!.guid' : 'AssetGuid.derive(context.packageId, key)'};
    const projection = projectScene(await generateScene(args));
    const outputs: Record<string, MeshAsset | MaterialAsset | SceneAsset | TextureAsset | SamplerAsset> = {}
    const textures = collectMaterialTextures(projection.materials)
    const textureKeys = new Map(textures.map(t => [surfaceTextureKey(t.source), 'texture/' + t.key]))
    for (const { key, source } of textures) outputs['texture/' + key] = {
      kind: 'texture', ${v1 ? 'width: source.width, height: source.height,' : "shape: { viewDimension: '2d', extent: { width: source.width, height: source.height } },"}
      format: source.colorSpace === 'srgb' ? 'rgba8unorm-srgb' : 'rgba8unorm',
      data: decodeSurfaceTexture(source), colorSpace: source.colorSpace, ${v1 ? 'mipmap: true' : "mips: { kind: 'generate' }"},
    }
    if (textures.length) outputs['sampler/surface-repeat'] = {
      kind: 'sampler', magFilter: 'linear', minFilter: 'linear', mipmapFilter: 'linear',
      addressModeU: 'repeat', addressModeV: 'repeat', maxAnisotropy: 8,
    }
    // Scene-global materials, emitted once each. \`projection.materials\` is
    // deduped by (material name, appearance), so meshes sharing a rule share the
    // asset instead of each carrying a private copy.
    const materialKeyFor = (at: number): string => \`material/\${projection.materials[at]!.key}\`
    for (const [at, material] of projection.materials.entries()) {
      const { surface } = material
      const cutout = (surface.alphaCutoff ?? 0) > 0
      const transparent = !cutout && surface.baseColor[3] < 1
      outputs[materialKeyFor(at)] = Materials.standard({
        // SurfaceAppearance and the Three.js viewport both use working/linear RGB.
        ${v1 ? "colorSpace: 'linear'," : ''}
        ...Object.fromEntries(SURFACE_TEXTURE_CHANNELS.filter(k => surface[k]).map(k => {
          const source = surface[k]!
          return [k, { texture: AssetGuid.format(assetGuid(textureKeys.get(surfaceTextureKey(source))!)),
            sampler: AssetGuid.format(assetGuid('sampler/surface-repeat')),
            coordinates: { transform: { scale: source.scale ?? [1, 1] } } }]
        })),
        baseColor: [...surface.baseColor],
        roughness: surface.roughness,
        metallic: surface.metallic,
        ...(surface.alphaCutoff === undefined ? {} : { alphaCutoff: surface.alphaCutoff }),
        // Cutout cards share the preview's two-sided surface convention.
        ...(cutout ? { queue: 2450, renderState: { depthWriteEnabled: true, cullMode: 'none' } } : {}),
        ...(surface.emissive ? { emissive: [...surface.emissive] } : {}),
        ...(surface.emissiveIntensity === undefined ? {} : { emissiveIntensity: surface.emissiveIntensity }),
        ...(transparent ? {
          queue: 3000,
          castShadow: false,
          renderState: {
            depthWriteEnabled: false,
            blend: {
              color: { srcFactor: 'src-alpha', dstFactor: 'one-minus-src-alpha', operation: 'add' },
              alpha: { srcFactor: 'one', dstFactor: 'one-minus-src-alpha', operation: 'add' },
            },
          },
        } : {}),
      })
    }
    const entities: ${v1 ? 'SceneEntity[] = [\n      {\n        localId: AXIS_ROOT as LocalEntityId,' : 'Record<string, SceneEntity> = {\n      [AXIS_ROOT]: {'}
        components: {
          Name: { value: ${JSON.stringify(packName)} },
          Transform: { pos: [0, 0, 0], scale: [1, 1, 1], quat: [...Y_UP_QUAT] },
        },
      },
    ${v1 ? ']' : '}'}
    const meshKeys = new Map<object,string>()
    for (const [index, entity] of projection.entities.entries()) {
      ${v1 ? 'const localId = (index + 1) as LocalEntityId' : "const entityKey = 'node/' + entity.slug"}
      const parent = entity.parentIndex === null ? AXIS_ROOT : ${v1 ? 'entity.parentIndex + 1' : "'node/' + projection.entities[entity.parentIndex]!.slug"}
      // Keep the author's parent-local TRS and mesh coordinates.
      const components: { -readonly [K in keyof SceneEntity['components']]: SceneEntity['components'][K] } = {
        Name: { value: entity.name },
        Transform: { pos: [...entity.translation], scale: [...(entity.transform.scale ?? [1, 1, 1])], quat: [...(entity.transform.quat ?? [0, 0, 0, 1])] },
        ChildOf: { parent },
      }
      if (entity.mesh) {
        const meshKey = meshKeys.get(entity.mesh) ?? \`mesh/\${entity.slug}\`
        meshKeys.set(entity.mesh,meshKey)
        if (!outputs[meshKey]) {
        const built = meshFromInterleaved(entity.mesh.vertices, entity.mesh.indices)
        if (!built.ok) return built
        // One submesh + one slot per run. \`meshFromInterleaved\` returns a single
        // submesh over the whole buffer, so both tables are overwritten here.
        // Field shape follows the engine's own multi-primitive producer,
        // \`packages/gltf/src/bridge.ts\`: vertexCount carries the mesh's vertex
        // count (the non-indexed draw fallback) and materialSlot indexes
        // \`materialSlots\`.
        const runs = entity.mesh.runs
        const attributes = {
          ...built.value.attributes,
          ...(entity.mesh.colors ? { color: entity.mesh.colors } : {}),
        }
        let vertices = built.value.vertices
        if (entity.mesh.colors) {
          const packed = packInterleavedVertexAttributes(attributes, entity.mesh.vertexCount)
          if (!packed.ok) return packed
          vertices = packed.value.vertices
        }
        outputs[meshKey] = {
          ...built.value,
          vertices,
          attributes,
          submeshes: runs.map((run, slot) => ({
            indexOffset: run.indexOffset,
            indexCount: run.indexCount,
            vertexCount: entity.mesh!.vertexCount,
            topology: 'triangle-list' as const,
            materialSlot: slot,
          })),
          materialSlots: runs.map((run, slot) => ({
            slotName: runs.length === 1 ? 'surface' : \`surface-\${slot}\`,
            sourceKey: projection.materials[run.material]!.key + '/slot-' + slot,
            defaultMaterial: assetGuid(materialKeyFor(run.material)),
          })),
        }
        }
        components.MeshFilter = { assetHandle: AssetGuid.format(assetGuid(meshKey)) }
        // Empty \`materials\` falls back to the mesh's own slot defaults above.
        components.MeshRenderer = { materials: [] }
      }
      ${v1 ? 'entities.push({ localId, components })' : 'entities[entityKey] = { components }'}
    }
    if (${input.includeDefaultLighting ?? true}) {
    ${v1 ? 'const sunId = projection.entities.length + 1\n    entities.push({\n      localId: sunId as LocalEntityId,' : "entities['lighting/sun'] = {"}
      components: {
        Name: { value: 'Sun' },
        DirectionalLight: {
          direction: [...SUN_OUTGOING_DIRECTION],
          color: [1, 0.98, 0.93],
          intensity: 3.2,
          castShadow: true,
          cascadeCount: 3,
          splitLambda: 0.72,
          cascadeBlend: 0.18,
          mapSize: 2048,
          // Directional receiver bias is in normalized shadow depth, not metres.
          // Centimetre-scale values here erase contact shadows at city coverage.
          depthBias: 0.00005,
          normalBias: 0.0001,
          shadowDistance: shadowDistanceFor(projection.bounds.diagonal),
          pcfKernelSize: 3,
        },
      },
    ${v1 ? '})\n    entities.push({\n      localId: (sunId + 1) as LocalEntityId,' : "}\n    entities['lighting/skylight'] = {"}
      components: {
        Name: { value: 'Skylight' },
        Skylight: { color: [1, 1, 1], intensity: 0.8 },
      },
    ${v1 ? '})' : '}'}
    }
    outputs[SCENE_KEY] = { kind: 'scene', entities }
    return ok(outputs)
  },
}${v1 ? ' satisfies ScriptablePackDefinition' : ')'}
`
}
