import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'valleyHeightfield',
  contractVersion: '1.2.0',
  opId: 'valley_heightfield',
  description: 'Procedurally generate a continuous mountain valley elevation heightfield with a gentle meadow floor, carved riverbed, terraced slopes and flanking alpine ridges.',
  inputs: [
    { name: 'width', type: 'number', access: 'item', defaultValue: 128, label: '宽度', mode: 'parameter' },
    { name: 'height', type: 'number', access: 'item', defaultValue: 128, label: '长度', mode: 'parameter' },
    { name: 'valleyDepth', type: 'number', access: 'item', defaultValue: 42, label: '山脊落差', mode: 'parameter', control: true },
    { name: 'valleyWidth', type: 'number', access: 'item', defaultValue: 32, label: '谷底宽度', mode: 'parameter', control: true },
    { name: 'riverDepth', type: 'number', access: 'item', defaultValue: 2.2, label: '河流深度', mode: 'parameter', control: true },
    { name: 'riverWidth', type: 'number', access: 'item', defaultValue: 8, label: '河流宽度', mode: 'parameter', control: true },
    { name: 'ridgeNoise', type: 'number', access: 'item', defaultValue: 4.6, label: '山脊起伏', mode: 'parameter', control: true },
    { name: 'seed', type: 'number', access: 'item', defaultValue: 27, label: '随机种子', mode: 'parameter', control: true },
    { name: 'baseElevation', type: 'number', access: 'item', defaultValue: 3, label: '谷底标高', mode: 'parameter' },
    { name: 'peaks', type: 'point2d', access: 'list', label: '语义山峰控制点', mode: 'parameter' },
    { name: 'riverPoints', type: 'point2d', access: 'list', label: '河流中心线' },
    { name: 'erosionStrength', type: 'number', access: 'item', defaultValue: 0.7, label: '冲刷侵蚀强度', mode: 'parameter' },
    { name: 'terraceSteps', type: 'number', access: 'item', defaultValue: 6, label: '梯田台阶数', mode: 'parameter' },
    { name: 'plazaCenter', type: 'point2d', access: 'item', label: '广场中心' },
    { name: 'plazaRadius', type: 'number', access: 'item', defaultValue: 7.4, label: '广场半径', mode: 'parameter' },
  ],
  outputs: [
    { name: 'heightGrid', type: 'grid', access: 'item', label: '高度场' },
    { name: 'valleyMask', type: 'grid', access: 'item', label: '谷底掩码' },
    { name: 'riverMask', type: 'grid', access: 'item', label: '河流掩码' },
    { name: 'terraceMask', type: 'grid', access: 'item', label: '梯田掩码' },
    { name: 'cliffMask', type: 'grid', access: 'item', label: '悬崖掩码' },
    { name: 'forestMask', type: 'grid', access: 'item', label: '森林掩码' },
    { name: 'buildableMask', type: 'grid', access: 'item', label: '可建区域掩码' },
    { name: 'slopeGrid', type: 'grid', access: 'item', label: '坡度场' },
    { name: 'minElevation', type: 'number', access: 'item', label: '最低海拔' },
    { name: 'maxElevation', type: 'number', access: 'item', label: '最高海拔' },
  ],
  deterministic: true,
})
