import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  functionName: 'proceduralVillageLayout',
  contractVersion: '1.0.0',
  opId: 'procedural_village_layout',
  description: 'Intelligently generate collision-free, zoning-aware procedural building layouts across hillside and valley terrain with road frontages, plaza rings, and contour terraces.',
  inputs: [
    { name: 'heightGrid', type: 'grid', access: 'item', required: true, label: '高度场' },
    { name: 'buildableMask', type: 'grid', access: 'item', label: '可建区域掩码' },
    { name: 'valleyMask', type: 'grid', access: 'item', label: '谷底掩码' },
    { name: 'terraceMask', type: 'grid', access: 'item', label: '梯田掩码' },
    { name: 'forestMask', type: 'grid', access: 'item', label: '森林掩码' },
    { name: 'slopeGrid', type: 'grid', access: 'item', label: '坡度场' },
    { name: 'roadPoints', type: 'point2d', access: 'list', label: '主道路线' },
    { name: 'ringPoints', type: 'point2d', access: 'list', label: '广场环路' },
    { name: 'trailPoints', type: 'point2d', access: 'list', label: '步道线' },
    { name: 'feederPoints', type: 'point2d', access: 'list', label: '山坡支路' },
    { name: 'millAccessPoints', type: 'point2d', access: 'list', label: '磨坊引道' },
    { name: 'riverPoints', type: 'point2d', access: 'list', label: '河流中心线' },
    { name: 'plazaCenter', type: 'point2d', access: 'item', label: '广场中心' },
    { name: 'towerPosition', type: 'point2d', access: 'item', label: '钟塔锚点' },
    { name: 'millPosition', type: 'point2d', access: 'item', label: '水车锚点' },
    { name: 'plazaRadius', type: 'number', access: 'item', defaultValue: 6.8, label: '广场半径', mode: 'parameter' },
    { name: 'targetCount', type: 'number', access: 'item', defaultValue: 32, label: '建筑目标数量', mode: 'parameter', control: true },
    { name: 'density', type: 'number', access: 'item', defaultValue: 1.0, label: '建筑密度', mode: 'parameter', control: true },
    { name: 'seed', type: 'number', access: 'item', defaultValue: 33, label: '随机种子', mode: 'parameter', control: true },
    { name: 'roadWidth', type: 'number', access: 'item', defaultValue: 3.2, label: '主路宽度', mode: 'parameter' },
    { name: 'riverWidth', type: 'number', access: 'item', defaultValue: 6.5, label: '河流宽度', mode: 'parameter' },
    { name: 'roadSetback', type: 'number', access: 'item', defaultValue: 2.8, label: '路边退距', mode: 'parameter', control: true },
    { name: 'minSpacing', type: 'number', access: 'item', defaultValue: 3.2, label: '栋间净距', mode: 'parameter', control: true },
  ],
  outputs: [
    { name: 'plots', type: 'list', access: 'item', label: '聚落宅基列表' },
    { name: 'points', type: 'point2d', access: 'list', label: '宅基点位' },
    { name: 'yaws', type: 'number', access: 'list', label: '建筑朝向' },
    { name: 'types', type: 'string', access: 'list', label: '建筑类型' },
    { name: 'count', type: 'number', access: 'item', label: '生成建筑数' },
  ],
  deterministic: true,
})
