export {
  FIRST_BATCH_ITEM_TYPES,
  GEOMETRY_KINDS,
  HANGABLE_GEOMETRY_KINDS,
  OPERATING_GEOMETRY_KINDS,
  GRAPH_SHAPE_PROJECTION,
  LIST_ALIAS_TYPES,
  SCENE_CONTENT_SCHEMAS,
  asItem,
  asList,
  geometryKind,
  graphAccessForTsShape,
  isGeometry,
  isGrid,
  isHangableGeometryKind,
  isHeightfield,
  isOperatingGeometryKind,
  type Geometry,
  type GeometryKind,
  type GeometryMesh,
  type GeometryNetwork,
  type GeometryNetwork3d,
  type GeometryNetworkEdge,
  type GeometryPlane,
  type GeometryPoint,
  type GeometryPoint2d,
  type GeometryPoint3d,
  type GeometryPolygon,
  type GeometryPolygon3d,
  type GeometryPolyline,
  type GeometryPolyline3d,
  type GeometrySpline,
  type GeometrySpline3d,
  type GeometryVoxel,
  type Grid,
  type Heightfield,
  type Point2d,
  type Point3d,
  isShapeBranch,
  isShapeTree,
  shapeTreeFromItem,
  shapeTreeFromList,
  type Item,
  type List,
  type SceneContent,
  type SceneContentSchema,
  type SceneGraph,
  isNumericBuffer,
  type SceneTransform,
  type FloatBuffer,
  type IndexBuffer,
  type SceneMesh,
  type SceneNode,
  type ScenePortValue,
  type SceneNodeContent,
  type SceneNodeId,
  type SceneTree,
  type SurfaceAppearance,
  type SurfaceRun,
  type ShapeBranch,
  type ShapeTree,
  type TsShapeLayer,
} from '@forgeax/scene-authoring'

export {
  allocateSpans,
  segmentRun,
  deriveSeed,
  localFrame,
  fitAnchor,
  boundsRelation,
  HOST_FUNCTION_NAMES,
  HOST_FUNCTION_OP_IDS,
  HOST_PRIMARY_OUTPUT,
  primaryOutputPort,
  unwrapPrimaryResult,
  SCENE_CALL_ID,
  SCENE_CALL_PORT,
  point2d,
  basePlane,
  polyline2d,
  spline2d,
  polygon2d,
  network2d,
  point3d,
  polyline3d,
  spline3d,
  polygon3d,
  network3d,
  geometryMask,
  createGrid,
  gridFill,
  gridGradient,
  gridDiamondSquare,
  gridMidpoint,
  hashNoise,
  valueNoise,
  valueCubicNoise,
  perlinNoise,
  openSimplex2Noise,
  openSimplex2sNoise,
  cellularNoise,
  gridAdd,
  gridSub,
  gridMul,
  gridMin,
  gridMax,
  gridLerp,
  gridChoose,
  gridMaskDiff,
  gridMaskUnion,
  gridAbs,
  gridNeg,
  gridClamp,
  gridRemap,
  gridSmoothstep,
  gridQuantize,
  gridBlur,
  gridSharpen,
  gridMedian,
  gridNeighborhoodMin,
  gridNeighborhoodMax,
  gridDilate,
  gridErodeMorph,
  gridOpen,
  gridClose,
  gridMajority,
  gridOutline,
  gridSlope,
  gridAspect,
  gridCurvature,
  gridThreshold,
  gridRangeSelect,
  gridEdge,
  gridBBox,
  gridStats,
  gridDistance,
  gridResize,
  gridComponents,
  gridZonalMean,
  bindSceneHostGlobals,
  createSceneRunHost,
  currentSceneHost,
  defaultGeneratorContext,
  defineRecordedGenerator,
  heightfield,
  heightfieldExplode,
  heightfieldSetMask,
  heightfieldMesh,
  box,
  transform,
  placeOnGround,
  liftToSurface,
  surfaceBand,
  emptyScene,
  invoke,
  runWithSceneHost,
  sceneNode,
  sceneOutput,
  addChild,
  sampleHeight,
  sampleSurface,
  collectArgRefs,
  hostResultError,
  serializeArgs,
  tagResult,
  type HostFunctionName,
  type HostImpl,
  type SceneArgRef,
  type SceneCallRecord,
  type SceneRunHost,
} from './host.js'

export {
  applySceneSourceEdits,
  orderReferencedBindings,
  rewriteLiteralPortAccess,
  type ApplySourceEditsResult,
  type SourceEdit,
} from './writeback.js'

export {
  findSceneSite,
  inspectArgReferences,
  inspectSceneSource,
  type SceneInspectArg,
  type SceneInspectSite,
} from './inspect.js'

export {
  displayGraphToKernel,
  isEnumLiteralArgument,
  opIdForFunction,
  projectTraceToDisplayGraph,
  type DisplayEdge,
  type DisplayGraph,
  type DisplayNode,
  type SourceMapProjection,
} from './projection.js'

export {
  bundleSceneModule,
  evaluateSceneBundle,
  runSceneModule,
  type RunSceneModuleInput,
  type RunSceneModuleResult,
} from './runner.js'

export {
  diagnoseSceneSemantics,
} from './semantics.js'

export {
  diagnoseScenePlacement,
  isSceneSpatialCode,
  isSceneSpatialFailCode,
  SCENE_SPATIAL_CODES,
  SCENE_SPATIAL_FAIL_CODES,
  SCENE_SPATIAL_ADVISORY_CODES,
} from './spatial.js'

export {
  diagnoseRoadStructures,
  SCENE_ROAD_FAIL_CODES,
  SCENE_ROAD_ADVISORY_CODES,
} from './road.js'

export {
  collectImportSpecifiers,
  diagnoseSceneConventions,
  resolveProjectImport,
  sceneSourceKind,
} from './convention.js'

export { defineMaterial, paintSurface, bindMaterialHostGlobals } from './material.js'

export { compilePortableScene, assertPortableInputs } from './portable.js'
