/** Scene port type tokens so `type: NumberValue` is valid at runtime without imports. */
export const Scene = 'Scene'
export const NumberValue = 'NumberValue'
export const StringValue = 'StringValue'
export const BooleanValue = 'BooleanValue'
export const Grid = 'Grid'
export const Heightfield = 'Heightfield'
export const Point2d = 'Point2d'
/** Leftover name. Triangle payloads live on Geometry kind mesh. */
export const Mesh = 'Geometry'
export const Geometry = 'Geometry'
export const NumberList = 'NumberList'
export const StringList = 'StringList'
export const Any = 'Any'

export const number = 'NumberValue'
export const string = 'StringValue'
export const boolean = 'BooleanValue'
export const grid = 'Grid'
export const heightfield = 'Heightfield'
export const mesh = 'Geometry'
export const geometry = 'Geometry'
export const any = 'Any'
export const point = 'Point2d'
export const scene = 'Scene'
