/** Scene port type tokens so `type: NumberValue` is valid at runtime without imports. */
export const Scene = 'Scene'
export const NumberValue = 'NumberValue'
export const StringValue = 'StringValue'
export const BooleanValue = 'BooleanValue'
export const Grid = 'Grid'
export const Point2d = 'Point2d'
export const Mesh = 'Mesh'
export const NumberList = 'NumberList'
export const StringList = 'StringList'
export const Any = 'Any'
export const Plane = 'Plane'
export const WorkGrid = 'WorkGrid'
export const RegionSet = 'RegionSet'
export const RoadNetwork = 'RoadNetwork'
export const ParcelSet = 'ParcelSet'
export const PlacementSet = 'PlacementSet'
export const Reserved = 'Reserved'
